### ISSUE TITLE
Problem at 'node util.js package' command

### ISSUE THREAD

**Issue by dinosaw** [RyanTheAllmighty/Allmighty-Twitch-Toolbox#1]
Hello!

I'm having a bit of trouble getting this to work. I was wondering if you could possibly help me out if I provided you with my logs. As a side note, I don't think I have `nw` installed correctly, but I don't believe that would be causing the problem I'm having at `node util.js package`. If you have any insight as to what I'm doing wrong, that would be great!

**Version Check**

```
[root@server ~/allmighty]# node -v
v0.10.39
[root@server ~/allmighty]# npm -v
1.4.28
[root@server ~/allmighty]# nw -v
/root/.nvm/v0.10.39/lib/node_modules/nw/nwjs/nw: error while loading shared libraries: libgconf-2.so.4: cannot open shared object file: No such file or directory
```

**Git Clone**

```
[root@server ~/allmighty]# git clone https://github.com/RyanTheAllmighty/Allmighty-Twitch-Toolbox.git .
git: /usr/local/lib/libz.so.1: no version information available (required by git)
Initialized empty Git repository in /root/allmighty/.git/
git-remote-https: /usr/local/lib/libz.so.1: no version information available (required by git-remote-https)
git: /usr/local/lib/libz.so.1: no version information available (required by git)
remote: Counting objects: 1689, done.
remote: Compressing objects: 100% (541/541), done.
git: /usr/local/lib/libz.so.1: no version information available (required by git)
remote: Total 1689 (delta 398), reused 0 (delta 0), pack-reused 1142
Receiving objects: 100% (1689/1689), 2.52 MiB, done.
Resolving deltas: 100% (1149/1149), done.
```

**NPM Install**

```
[root@server ~/allmighty]# npm install

> ws@0.6.5 install /root/allmighty/node_modules/obs-remote/node_modules/ws
> (node-gyp rebuild 2> builderror.log) || (exit 0)

make: Entering directory `/root/allmighty/node_modules/obs-remote/node_modules/ws/build'
  CXX(target) Release/obj.target/bufferutil/src/bufferutil.o
  SOLINK_MODULE(target) Release/obj.target/bufferutil.node
  SOLINK_MODULE(target) Release/obj.target/bufferutil.node: Finished
  COPY Release/bufferutil.node
  CXX(target) Release/obj.target/validation/src/validation.o
  SOLINK_MODULE(target) Release/obj.target/validation.node
  SOLINK_MODULE(target) Release/obj.target/validation.node: Finished
  COPY Release/validation.node
make: Leaving directory `/root/allmighty/node_modules/obs-remote/node_modules/ws/build'
npm WARN engine hoek@2.16.3: wanted: {"node":">=0.10.40"} (current: {"node":"0.10.39","npm":"1.4.28"})
npm WARN engine cryptiles@2.0.5: wanted: {"node":">=0.10.40"} (current: {"node":"0.10.39","npm":"1.4.28"})
npm WARN engine boom@2.10.1: wanted: {"node":">=0.10.40"} (current: {"node":"0.10.39","npm":"1.4.28"})
\
> utf-8-validate@1.2.1 install /root/allmighty/node_modules/socket.io/node_modules/engine.io/node_modules/ws/node_modules/utf-8-validate
> node-gyp rebuild

make: Entering directory `/root/allmighty/node_modules/socket.io/node_modules/engine.io/node_modules/ws/node_modules/utf-8-validate/build'
  CXX(target) Release/obj.target/validation/src/validation.o
  SOLINK_MODULE(target) Release/obj.target/validation.node
  SOLINK_MODULE(target) Release/obj.target/validation.node: Finished
  COPY Release/validation.node
make: Leaving directory `/root/allmighty/node_modules/socket.io/node_modules/engine.io/node_modules/ws/node_modules/utf-8-validate/build'
|
> bufferutil@1.2.1 install /root/allmighty/node_modules/socket.io/node_modules/engine.io/node_modules/ws/node_modules/bufferutil
> node-gyp rebuild

make: Entering directory `/root/allmighty/node_modules/socket.io/node_modules/engine.io/node_modules/ws/node_modules/bufferutil/build'
  CXX(target) Release/obj.target/bufferutil/src/bufferutil.o
  SOLINK_MODULE(target) Release/obj.target/bufferutil.node
  SOLINK_MODULE(target) Release/obj.target/bufferutil.node: Finished
  COPY Release/bufferutil.node
make: Leaving directory `/root/allmighty/node_modules/socket.io/node_modules/engine.io/node_modules/ws/node_modules/bufferutil/build'

> utf-8-validate@1.2.1 install /root/allmighty/node_modules/socket.io-client/node_modules/engine.io-client/node_modules/ws/node_modules/utf-8-validate
> node-gyp rebuild

make: Entering directory `/root/allmighty/node_modules/socket.io-client/node_modules/engine.io-client/node_modules/ws/node_modules/utf-8-validate/build'
  CXX(target) Release/obj.target/validation/src/validation.o
  SOLINK_MODULE(target) Release/obj.target/validation.node
  SOLINK_MODULE(target) Release/obj.target/validation.node: Finished
  COPY Release/validation.node
make: Leaving directory `/root/allmighty/node_modules/socket.io-client/node_modules/engine.io-client/node_modules/ws/node_modules/utf-8-validate/build'

> bufferutil@1.2.1 install /root/allmighty/node_modules/socket.io-client/node_modules/engine.io-client/node_modules/ws/node_modules/bufferutil
> node-gyp rebuild

make: Entering directory `/root/allmighty/node_modules/socket.io-client/node_modules/engine.io-client/node_modules/ws/node_modules/bufferutil/build'
  CXX(target) Release/obj.target/bufferutil/src/bufferutil.o
  SOLINK_MODULE(target) Release/obj.target/bufferutil.node
  SOLINK_MODULE(target) Release/obj.target/bufferutil.node: Finished
  COPY Release/bufferutil.node
make: Leaving directory `/root/allmighty/node_modules/socket.io-client/node_modules/engine.io-client/node_modules/ws/node_modules/bufferutil/build'
node-soundcloud@0.0.3 node_modules/node-soundcloud

giantbombapi@1.0.0 node_modules/giantbombapi

twitch-api@0.4.3 node_modules/twitch-api

ncp@2.0.0 node_modules/ncp

async@1.5.0 node_modules/async

grunt-mocha-test@0.12.7 node_modules/grunt-mocha-test
└── hooker@0.2.3

tmp@0.0.28 node_modules/tmp
└── os-tmpdir@1.0.1

mkdirp@0.5.1 node_modules/mkdirp
└── minimist@0.0.8

grunt-contrib-jshint@0.11.3 node_modules/grunt-contrib-jshint
└── hooker@0.2.3

accounting@0.4.1 node_modules/accounting

body-parser@1.14.1 node_modules/body-parser
├── bytes@2.1.0
├── content-type@1.0.1
├── depd@1.1.0
├── on-finished@2.3.0 (ee-first@1.1.1)
├── http-errors@1.3.1 (inherits@2.0.1, statuses@1.2.1)
├── raw-body@2.1.4 (unpipe@1.0.0)
├── debug@2.2.0 (ms@0.7.1)
├── qs@5.1.0
├── type-is@1.6.9 (media-typer@0.3.0, mime-types@2.1.7)
└── iconv-lite@0.4.12

del@2.0.2 node_modules/del
├── is-path-cwd@1.0.0
├── object-assign@4.0.1
├── pify@2.3.0
├── pinkie-promise@1.0.0 (pinkie@1.0.0)
├── is-path-in-cwd@1.0.0 (is-path-inside@1.0.0)
├── rimraf@2.4.3 (glob@5.0.15)
└── globby@3.0.1 (arrify@1.0.0, array-union@1.0.1, glob@5.0.15)

obs-remote@1.0.1 node_modules/obs-remote
└── ws@0.6.5 (options@0.0.6, ultron@1.0.2, nan@1.4.3)

chai@3.4.0 node_modules/chai
├── assertion-error@1.0.1
├── type-detect@1.0.0
└── deep-eql@0.1.3 (type-detect@0.1.1)

musicmetadata@2.0.2 node_modules/musicmetadata
├── deep-equal@0.2.1
├── through@2.3.8
├── filereader-stream@0.2.0 (inherits@1.0.0)
├── strtok2@1.0.1
└── sum-component@0.1.1 (to-function@2.0.6)

express@4.13.3 node_modules/express
├── escape-html@1.0.2
├── merge-descriptors@1.0.0
├── array-flatten@1.1.1
├── cookie@0.1.3
├── utils-merge@1.0.0
├── cookie-signature@1.0.6
├── methods@1.1.1
├── fresh@0.3.0
├── range-parser@1.0.3
├── vary@1.0.1
├── path-to-regexp@0.1.7
├── content-type@1.0.1
├── etag@1.7.0
├── parseurl@1.3.0
├── content-disposition@0.5.0
├── serve-static@1.10.0
├── depd@1.0.1
├── on-finished@2.3.0 (ee-first@1.1.1)
├── finalhandler@0.4.0 (unpipe@1.0.0)
├── qs@4.0.0
├── debug@2.2.0 (ms@0.7.1)
├── proxy-addr@1.0.8 (forwarded@0.1.0, ipaddr.js@1.0.1)
├── send@0.13.0 (destroy@1.0.3, statuses@1.2.1, ms@0.7.1, mime@1.3.4, http-errors@1.3.1)
├── type-is@1.6.9 (media-typer@0.3.0, mime-types@2.1.7)
└── accepts@1.2.13 (negotiator@0.5.3, mime-types@2.1.7)

request@2.65.0 node_modules/request
├── aws-sign2@0.6.0
├── forever-agent@0.6.1
├── caseless@0.11.0
├── stringstream@0.0.5
├── oauth-sign@0.8.0
├── tunnel-agent@0.4.1
├── form-data@1.0.0-rc3
├── isstream@0.1.2
├── json-stringify-safe@5.0.1
├── extend@3.0.0
├── combined-stream@1.0.5 (delayed-stream@1.0.0)
├── node-uuid@1.4.3
├── qs@5.2.0
├── tough-cookie@2.2.0
├── http-signature@0.11.0 (assert-plus@0.1.5, asn1@0.1.11, ctype@0.5.3)
├── bl@1.0.0 (readable-stream@2.0.4)
├── har-validator@2.0.2 (pinkie-promise@1.0.0, commander@2.9.0, chalk@1.1.1, is-my-json-valid@2.12.2)
├── hawk@3.1.0 (cryptiles@2.0.5, sntp@1.0.9, boom@2.10.1, hoek@2.16.3)
└── mime-types@2.1.7 (mime-db@1.19.0)

nw-notify@0.2.2 node_modules/nw-notify
├── async@0.9.2
├── promise@6.1.0 (asap@1.0.0)
└── lodash@2.4.2

nedb@1.2.1 node_modules/nedb
├── async@0.2.10
├── binary-search-tree@0.2.4
└── underscore@1.4.4

mocha@2.3.3 node_modules/mocha
├── escape-string-regexp@1.0.2
├── supports-color@1.2.0
├── growl@1.8.1
├── commander@2.3.0
├── diff@1.4.0
├── debug@2.0.0 (ms@0.6.2)
├── mkdirp@0.5.0 (minimist@0.0.8)
├── glob@3.2.3 (inherits@2.0.1, graceful-fs@2.0.3, minimatch@0.2.14)
└── jade@0.26.3 (commander@0.6.1, mkdirp@0.3.0)

sinon@1.17.2 node_modules/sinon
├── formatio@1.1.1
├── samsam@1.1.2
├── lolex@1.3.2
└── util@0.10.3 (inherits@2.0.1)

jade@1.11.0 node_modules/jade
├── character-parser@1.2.1
├── void-elements@2.0.1
├── commander@2.6.0
├── jstransformer@0.0.2 (is-promise@2.1.0, promise@6.1.0)
├── constantinople@3.0.2 (acorn@2.5.2)
├── clean-css@3.4.6 (commander@2.8.1, source-map@0.4.4)
├── transformers@2.1.0 (promise@2.0.0, css@1.0.8, uglify-js@2.2.5)
├── with@4.0.3 (acorn@1.2.2, acorn-globals@1.0.9)
└── uglify-js@2.5.0 (uglify-to-browserify@1.0.2, async@0.2.10, yargs@3.5.4, source-map@0.5.3)

archiver@0.14.4 node_modules/archiver
├── buffer-crc32@0.2.5
├── lazystream@0.1.0
├── readable-stream@1.0.33 (string_decoder@0.10.31, inherits@2.0.1, core-util-is@1.0.1, isarray@0.0.1)
├── zip-stream@0.5.2 (compress-commons@0.2.9)
├── async@0.9.2
├── tar-stream@1.1.5 (xtend@4.0.1, bl@0.9.4, end-of-stream@1.1.0)
├── glob@4.3.5 (inherits@2.0.1, once@1.3.2, inflight@1.0.4, minimatch@2.0.10)
└── lodash@3.2.0

lodash@3.10.1 node_modules/lodash

socket.io@1.3.7 node_modules/socket.io
├── debug@2.1.0 (ms@0.6.2)
├── has-binary-data@0.1.3 (isarray@0.0.1)
├── socket.io-adapter@0.3.1 (object-keys@1.0.1, debug@1.0.2, socket.io-parser@2.2.2)
├── socket.io-parser@2.2.4 (isarray@0.0.1, debug@0.7.4, component-emitter@1.1.2, benchmark@1.0.0, json3@3.2.6)
└── engine.io@1.5.4 (base64id@0.1.0, debug@1.0.3, engine.io-parser@1.2.2, ws@0.8.0)

grunt-cli@0.1.13 node_modules/grunt-cli
├── nopt@1.0.10 (abbrev@1.0.7)
├── resolve@0.3.1
└── findup-sync@0.1.3 (glob@3.2.11, lodash@2.4.2)

socket.io-client@1.3.7 node_modules/socket.io-client
├── to-array@0.1.3
├── indexof@0.0.1
├── component-bind@1.0.0
├── debug@0.7.4
├── backo2@1.0.2
├── object-component@0.0.3
├── component-emitter@1.1.2
├── has-binary@0.1.6 (isarray@0.0.1)
├── parseuri@0.0.2 (better-assert@1.0.2)
├── socket.io-parser@2.2.4 (isarray@0.0.1, benchmark@1.0.0, json3@3.2.6)
└── engine.io-client@1.5.4 (component-inherit@0.0.3, debug@1.0.4, xmlhttprequest@1.5.0, parsejson@0.0.1, parseqs@0.0.2, engine.io-parser@1.2.2, parseuri@0.0.4, has-cors@1.0.3, ws@0.8.0)

moment@2.10.6 node_modules/moment

grunt@0.4.5 node_modules/grunt
├── which@1.0.9
├── dateformat@1.0.2-1.2.3
├── eventemitter2@0.4.14
├── getobject@0.1.0
├── rimraf@2.2.8
├── colors@0.6.2
├── async@0.1.22
├── grunt-legacy-util@0.2.0
├── nopt@1.0.10 (abbrev@1.0.7)
├── exit@0.1.2
├── hooker@0.2.3
├── minimatch@0.2.14 (sigmund@1.0.1, lru-cache@2.7.0)
├── glob@3.1.21 (inherits@1.0.2, graceful-fs@1.2.3)
├── lodash@0.9.2
├── coffee-script@1.3.3
├── underscore.string@2.2.1
├── iconv-lite@0.2.11
├── js-yaml@2.0.5 (argparse@0.1.16, esprima@1.0.4)
├── grunt-legacy-log@0.1.2 (grunt-legacy-log-utils@0.1.1, underscore.string@2.3.3, lodash@2.4.2)
└── findup-sync@0.1.3 (glob@3.2.11, lodash@2.4.2)

jshint@2.8.0 node_modules/jshint
├── strip-json-comments@1.0.4
├── exit@0.1.2
├── console-browserify@1.1.0 (date-now@0.1.4)
├── shelljs@0.3.0
├── minimatch@2.0.10 (brace-expansion@1.1.1)
├── cli@0.6.6 (glob@3.2.11)
├── htmlparser2@3.8.3 (domelementtype@1.3.0, entities@1.0.0, domhandler@2.3.0, readable-stream@1.1.13, domutils@1.5.1)
└── lodash@3.7.0

autolinker@0.18.3 node_modules/autolinker

ffmetadata@1.3.0 node_modules/ffmetadata
├── stream-filter@1.0.0
├── split@0.2.10
├── through@2.3.8
├── stream-combiner@0.0.2 (duplexer@0.0.4)
└── concat-stream@1.0.1 (bops@0.0.6)
```

**node util.js package**

```
[root@server ~/allmighty]# node util.js package

/root/allmighty/util.js:45
        let toArchive = [
        ^^^
SyntaxError: Unexpected strict mode reserved word
    at Module._compile (module.js:439:25)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Function.Module.runMain (module.js:497:10)
    at startup (node.js:119:16)
    at node.js:935:3
```

**Comment by RyanTheAllmighty** [comment]
Looks like you're running node version v0.10.39. Needs 4.0 or higher due to using ES6 features. Might work on 0.x versions with the harmony flag, but not sure.
